// Estilos globales del sitio (se cargan una sola vez desde el layout raíz).
import './globals.css';
import type { Metadata } from 'next';
// Fuente Inter optimizada por Next.js (self-hosted, sin request extra a Google Fonts en runtime).
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// Metadata por defecto de Next.js (título/descripción/OG/Twitter cards).
// Nota: sigue con los valores placeholder de "create-next-app"; no se personalizó
// todavía para este sitio de noticias (título, imágenes OG, etc.).
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
};

// Layout raíz (App Router): envuelve TODAS las páginas de la app.
// Es el único lugar donde se define <html>/<body>, por eso acá van
// las cosas globales (fuente, estilos, metadata) en vez de repetirlas
// en cada página. No hay providers (contexto/tema/etc.) por ahora:
// "children" se renderiza directo dentro del <body>.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
